# Site settings
title: Kurt Samuels Jr
logo: /assets/msds.png

description: My Personal Website
# Show downloads
show_downloads: true

# Theme settings
theme: jekyll-theme-dinky

# External links
#external_links:
 # - name: LinkedIn
    #url: https://www.linkedin.com/in/kurt-jr

# GitHub links
github:
  zip_url: /assets/msdsResume.pdf
  #another_url: https://www.linkedin.com/in/kurt-jr

# Plugins
plugins:
  - jekyll-remote-theme
